AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SBE Lambda Encoder with Runtime Code Generation

Globals:
  Function:
    Timeout: 300
    MemorySize: 3008

Resources:
  SbeEncoderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: sbe-encoder:latest
      MemorySize: 3008
      Timeout: 300
      EphemeralStorage:
        Size: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
      Description: Encodes messages using SBE with runtime code generation
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  SbeEncoderFunction:
    Description: "SBE Encoder Lambda Function ARN"
    Value: !GetAtt SbeEncoderFunction.Arn
  SbeEncoderFunctionIamRole:
    Description: "Implicit IAM Role created for SBE Encoder function"
    Value: !GetAtt SbeEncoderFunctionRole.Arn
