// Auto-generated from Foundry contract compilation
// Do not edit this file manually - run 'npm run generate-abis' to regenerate

export const abi = [
  {
    "type": "function",
    "name": "deploy",
    "inputs": [
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "ptr",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "DataDeployed",
    "inputs": [
      {
        "name": "ptr",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "length",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  }
] as const;

export type DataContractFactoryAbi = typeof abi;
