// Auto-generated from Foundry contract compilation
// Do not edit this file manually - run 'npm run generate-abis' to regenerate

export const abi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "fixCBORChunk",
    "inputs": [
      {
        "name": "assetId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "start",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "size",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDescriptor",
    "inputs": [
      {
        "name": "assetId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct DescriptorRegistry.FixDescriptor",
        "components": [
          {
            "name": "fixMajor",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "fixMinor",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "fixRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "fixCBORPtr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fixCBORLen",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "schemaURI",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setDescriptor",
    "inputs": [
      {
        "name": "assetId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "d",
        "type": "tuple",
        "internalType": "struct DescriptorRegistry.FixDescriptor",
        "components": [
          {
            "name": "fixMajor",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "fixMinor",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "fixRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "fixCBORPtr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fixCBORLen",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "schemaURI",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AssetFIXCommitted",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "fixRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "schemaHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "fixCBORPtr",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "fixCBORLen",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetFIXUpdated",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "oldRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "newRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "newPtr",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  }
] as const;

export type DescriptorRegistryAbi = typeof abi;
