// Auto-generated from Foundry contract compilation
// Do not edit this file manually - run 'npm run generate-abis' to regenerate

export const abi = [] as const;

export type FixMerkleVerifierAbi = typeof abi;
