AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SBE encode/decode Lambda (Node + Java runtime codegen)

Globals:
  Function:
    Timeout: 300
    MemorySize: 3000

Resources:
  SbeNodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Description: Encode/decode FIX messages via SBE
      Events:
        Encode:
          Type: HttpApi
          Properties:
            Path: /encode
            Method: POST
        Decode:
          Type: HttpApi
          Properties:
            Path: /decode
            Method: POST
      Environment:
        Variables:
          SBE_TOOL_JAR: /opt/sbe/sbe-all.jar
          SBE_OUTPUT_DIR: /tmp/sbe-codecs
          SBE_LOG: "0"
    Metadata:
      Dockerfile: sam/Dockerfile
      DockerContext: ..
      DockerTag: sbe-node-lambda

Outputs:
  SbeNodeFunction:
    Description: "SBE encode/decode Lambda ARN"
    Value: !GetAtt SbeNodeFunction.Arn
